THEME_PROBLEMS = {
    "구글 애널리틱스 (이커머스)": [
        # 초급 (10문제)
        {"title": "1. 세션이 가장 많은 브라우저 찾기", "difficulty": "초급", "question": "ga_sessions 테이블을 사용하여, 가장 많은 세션을 발생시킨 브라우저(browser) 상위 3개와 그 세션 수를 조회하세요.", "hint": "GROUP BY를 사용하여 browser별로 묶고, COUNT(*)로 개수를 센 뒤 ORDER BY 내림차순 정렬과 LIMIT를 활용하세요.", "answer": "SELECT browser, COUNT(*) as session_count\nFROM ga_sessions\nGROUP BY browser\nORDER BY session_count DESC\nLIMIT 3;"},
        {"title": "2. 모바일 기기 사용자 수 확인", "difficulty": "초급", "question": "ga_sessions 테이블에서 device_category가 'mobile'인 세션의 총 개수를 조회하세요.", "hint": "WHERE 조건절을 사용하여 device_category 컬럼의 값을 필터링하고 COUNT 함수를 사용하세요.", "answer": "SELECT COUNT(*) as mobile_sessions\nFROM ga_sessions\nWHERE device_category = 'mobile';"},
        {"title": "3. 장바구니 담기 이벤트 건수 조회", "difficulty": "초급", "question": "ga_events 테이블에서 event_name이 'add_to_cart'인 이벤트가 총 몇 건 발생했는지 조회하세요.", "hint": "ga_events 테이블에서 WHERE 절로 event_name을 지정하면 됩니다.", "answer": "SELECT COUNT(*) as add_to_cart_count\nFROM ga_events\nWHERE event_name = 'add_to_cart';"},
        {"title": "4. 특정 사용자의 세션 기록 확인", "difficulty": "초급", "question": "ga_sessions 테이블에서 'user_0001' 사용자의 모든 세션을 가장 최신(session_datetime) 순으로 정렬하여 조회하세요.", "hint": "WHERE 절로 유저 아이디를 필터링하고 ORDER BY DESC를 사용하세요.", "answer": "SELECT *\nFROM ga_sessions\nWHERE user_id = 'user_0001'\nORDER BY session_datetime DESC;"},
        {"title": "5. 특정 브라우저 이벤트 조회", "difficulty": "초급", "question": "ga_sessions 테이블에서 'Safari' 브라우저로 접속한 세션들의 평균 페이지뷰(pageviews)를 조회하세요.", "hint": "WHERE 절에 브라우저 이름을 넣고 AVG() 함수를 사용하세요.", "answer": "SELECT AVG(pageviews) as avg_pageviews\nFROM ga_sessions\nWHERE browser = 'Safari';"},
        {"title": "6. 특정 기간 접속 세션 수", "difficulty": "초급", "question": "ga_sessions 테이블에서 '2023-01-01'부터 '2023-01-10' 사이에 발생한 세션의 개수를 조회하세요.", "hint": "WHERE 절에 날짜 범위를 지정하는 BETWEEN 연산자를 활용하세요.", "answer": "SELECT COUNT(*) as early_jan_sessions\nFROM ga_sessions\nWHERE session_date BETWEEN '2023-01-01' AND '2023-01-10';"},
        {"title": "7. 페이지뷰 상위 5개 세션", "difficulty": "초급", "question": "ga_sessions 테이블에서 페이지뷰(pageviews)가 가장 많은 상위 5개의 세션 ID와 페이지뷰 수를 조회하세요.", "hint": "ORDER BY로 페이지뷰를 내림차순 정렬하고 LIMIT 5를 적용하세요.", "answer": "SELECT session_id, pageviews\nFROM ga_sessions\nORDER BY pageviews DESC\nLIMIT 5;"},
        {"title": "8. 데스크톱 세션들의 총 페이지뷰", "difficulty": "초급", "question": "ga_sessions 테이블에서 device_category가 'desktop'인 세션들이 발생시킨 총 페이지뷰(pageviews)의 합을 구하세요.", "hint": "WHERE로 기기를 필터링하고 SUM() 함수를 사용하세요.", "answer": "SELECT SUM(pageviews) as total_desktop_pageviews\nFROM ga_sessions\nWHERE device_category = 'desktop';"},
        {"title": "9. 특정 출처(Source) 방문자 찾기", "difficulty": "초급", "question": "ga_sessions 테이블에서 source가 'google'인 세션들의 고유한 사용자(user_id) 수를 구하세요.", "hint": "COUNT() 함수 안에 DISTINCT 키워드를 사용하여 중복 사용자를 제거하세요.", "answer": "SELECT COUNT(DISTINCT user_id) as google_users\nFROM ga_sessions\nWHERE source = 'google';"},
        {"title": "10. 특정 유입 매체 이벤트", "difficulty": "초급", "question": "ga_sessions 테이블에서 medium이 'cpc'인 세션의 총 개수를 조회하세요.", "hint": "WHERE 절에서 medium을 'cpc'로 필터링하고 COUNT(*)를 적용하세요.", "answer": "SELECT COUNT(*) as cpc_sessions\nFROM ga_sessions\nWHERE medium = 'cpc';"},
        
        # 중급 (10문제)
        {"title": "11. 기기별 총 매출액 비교하기", "difficulty": "중급", "question": "ga_sessions와 transactions 테이블을 조인하여, 기기 카테고리(device_category)별 총 매출액(revenue)을 내림차순으로 조회하세요.", "hint": "두 테이블을 session_id 기준으로 JOIN하고, device_category별로 GROUP BY하여 revenue의 SUM()을 구하세요.", "answer": "SELECT s.device_category, SUM(t.revenue) as total_revenue\nFROM ga_sessions s\nJOIN transactions t ON s.session_id = t.session_id\nGROUP BY s.device_category\nORDER BY total_revenue DESC;"},
        {"title": "12. 가장 비싼 단일 결제 찾기", "difficulty": "중급", "question": "transactions 테이블에서 단일 결제 금액(revenue)이 가장 큰 주문의 transaction_id와 revenue를 조회하세요.", "hint": "ORDER BY revenue DESC로 정렬 후 LIMIT 1을 사용하면 쉽게 구할 수 있습니다.", "answer": "SELECT transaction_id, revenue\nFROM transactions\nORDER BY revenue DESC\nLIMIT 1;"},
        {"title": "13. 특정 상품별 판매량 집계", "difficulty": "중급", "question": "transactions 테이블에서 각 상품(product_name)별로 팔린 총 수량(quantity)을 구하고, 수량이 많은 순으로 정렬하세요.", "hint": "product_name으로 GROUP BY 하고, SUM(quantity)을 구해 내림차순 정렬하세요.", "answer": "SELECT product_name, SUM(quantity) as total_quantity\nFROM transactions\nGROUP BY product_name\nORDER BY total_quantity DESC;"},
        {"title": "14. 트래픽 소스별 방문 수", "difficulty": "중급", "question": "ga_sessions 테이블에서 트래픽 소스(source)별 방문 횟수를 구하되, 방문 횟수가 10번 이상인 소스만 내림차순으로 조회하세요.", "hint": "GROUP BY source 이후, HAVING 절을 사용하여 COUNT(*) >= 10 조건을 추가하세요.", "answer": "SELECT source, COUNT(*) as visit_count\nFROM ga_sessions\nGROUP BY source\nHAVING COUNT(*) >= 10\nORDER BY visit_count DESC;"},
        {"title": "15. 운영체제별 평균 페이지뷰", "difficulty": "중급", "question": "ga_sessions 테이블에서 운영체제(operating_system)별 평균 페이지뷰(pageviews)를 조회하세요.", "hint": "operating_system으로 그룹핑하고 AVG() 함수를 사용하세요.", "answer": "SELECT operating_system, AVG(pageviews) as avg_pageviews\nFROM ga_sessions\nGROUP BY operating_system;"},
        {"title": "16. 일별 세션 수 추이", "difficulty": "중급", "question": "ga_sessions 테이블에서 일자(session_date)별 발생한 총 세션 수를 구하고 날짜 오름차순으로 정렬하세요.", "hint": "날짜로 그룹화하고 개수를 세면 됩니다.", "answer": "SELECT session_date, COUNT(*) as daily_sessions\nFROM ga_sessions\nGROUP BY session_date\nORDER BY session_date ASC;"},
        {"title": "17. 대량 페이지뷰 세션 조회", "difficulty": "중급", "question": "ga_sessions 테이블에서 한 세션 내에 10페이지 이상(pageviews >= 10)을 조회한 세션들의 사용자 아이디(user_id)를 중복 없이 조회하세요.", "hint": "WHERE 조건절을 사용하고 DISTINCT 키워드를 사용하여 중복을 제거하세요.", "answer": "SELECT DISTINCT user_id\nFROM ga_sessions\nWHERE pageviews >= 10;"},
        {"title": "18. 매체(medium)별 결제 전환 세션 수", "difficulty": "중급", "question": "ga_sessions 테이블과 transactions 테이블을 조인하여, 각 medium(매체)별로 실제 결제가 일어난 고유 세션의 수를 구하세요.", "hint": "transactions 테이블과 조인한 후 COUNT(DISTINCT s.session_id)를 사용하여 중복 결제를 제외한 세션 수를 계산하세요.", "answer": "SELECT s.medium, COUNT(DISTINCT s.session_id) as converted_sessions\nFROM ga_sessions s\nJOIN transactions t ON s.session_id = t.session_id\nGROUP BY s.medium\nORDER BY converted_sessions DESC;"},
        {"title": "19. 가장 빈번하게 발생한 이벤트 상위 3개", "difficulty": "중급", "question": "ga_events 테이블에서 발생 횟수가 가장 많은 상위 3개의 이벤트 이름(event_name)과 횟수를 조회하세요.", "hint": "event_name으로 GROUP BY 한 후 개수를 내림차순 정렬하고 LIMIT 3을 사용하세요.", "answer": "SELECT event_name, COUNT(*) as event_count\nFROM ga_events\nGROUP BY event_name\nORDER BY event_count DESC\nLIMIT 3;"},
        {"title": "20. 여러 기기를 사용하는 유저 찾기", "difficulty": "중급", "question": "ga_sessions 테이블을 사용하여, 2가지 이상의 서로 다른 기기 종류(device_category)로 접속한 이력이 있는 사용자(user_id)를 조회하세요.", "hint": "user_id로 그룹화하고 HAVING COUNT(DISTINCT device_category) >= 2 조건을 사용하세요.", "answer": "SELECT user_id\nFROM ga_sessions\nGROUP BY user_id\nHAVING COUNT(DISTINCT device_category) >= 2;"},
        
        # 고급 (10문제)
        {"title": "21. 재방문 유저의 첫 결제액 찾기", "difficulty": "고급", "question": "각 유저가 발생시킨 여러 세션 중 첫 세션(session_datetime 기준)에서는 결제를 무시하고, '두 번째 이후의 세션'에서 발생시킨 첫 번째 결제 건의 transaction_id와 revenue를 찾으세요. (결제가 없는 유저는 제외하세요.)", "hint": "윈도우 함수 ROW_NUMBER()를 사용하여 세션별 순위를 매긴 CTE를 먼저 만들고, 해당 조건을 필터링한 뒤 transactions 테이블과 조인하세요.", "answer": "WITH SessionRank AS (\n    SELECT session_id, user_id, ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY session_datetime ASC) as rn\n    FROM ga_sessions\n), ReturnSessions AS (\n    SELECT session_id FROM SessionRank WHERE rn > 1\n), TxnRank AS (\n    SELECT t.transaction_id, t.revenue, ROW_NUMBER() OVER(PARTITION BY t.user_id ORDER BY t.transaction_date ASC) as txn_rn\n    FROM transactions t\n    JOIN ReturnSessions r ON t.session_id = r.session_id\n)\nSELECT transaction_id, revenue\nFROM TxnRank\nWHERE txn_rn = 1;"},
        {"title": "22. 장바구니 유기율(Abandonment Rate) 분석", "difficulty": "고급", "question": "이커머스에서 장바구니 이탈률은 매우 중요한 지표입니다. 전체 세션 중에서 'add_to_cart' 이벤트는 한 번이라도 발생했지만, 'purchase' 이벤트는 단 한 번도 발생하지 않은 세션들의 비율을 구하려고 합니다. 전체 장바구니 담기 세션 대비 미결제 세션의 비율(퍼센트)을 계산하여 'abandonment_rate'라는 컬럼으로 조회하세요.", "hint": "'add_to_cart' 세션과 'purchase' 세션을 분리하는 서브쿼리나 CTE를 만들고, LEFT JOIN하여 결제가 없는 경우(NULL)의 수를 전체 비율로 계산하세요. (소수점 연산을 고려하세요.)", "answer": "WITH CartSessions AS (\n    SELECT DISTINCT session_id \n    FROM ga_events \n    WHERE event_name = 'add_to_cart'\n), PurchaseSessions AS (\n    SELECT DISTINCT session_id \n    FROM ga_events \n    WHERE event_name = 'purchase'\n)\nSELECT \n    CAST((SELECT COUNT(*) FROM CartSessions c LEFT JOIN PurchaseSessions p ON c.session_id = p.session_id WHERE p.session_id IS NULL) AS FLOAT) \n    / (SELECT COUNT(*) FROM CartSessions) * 100 as abandonment_rate;"},
        {"title": "23. 일별 누적 매출 추이 집계", "difficulty": "고급", "question": "매일 일어난 일일 매출(revenue)의 합계를 구하고, 날짜순으로 정렬하여 첫 날부터 해당 날짜까지 누적된 '누적 매출액(Cumulative Revenue)'을 계산하세요. 결과는 날짜(transaction_date), 일일 매출, 누적 매출 3가지 컬럼으로 조회해야 합니다.", "hint": "먼저 GROUP BY로 일일 총 매출을 구하는 CTE를 작성한 뒤, 메인 쿼리에서 누적합을 구하는 윈도우 함수를 사용하세요.", "answer": "WITH DailyRev AS (\n    SELECT transaction_date, SUM(revenue) as daily_revenue\n    FROM transactions\n    GROUP BY transaction_date\n)\nSELECT transaction_date, daily_revenue,\n       SUM(daily_revenue) OVER(ORDER BY transaction_date) as cumulative_revenue\nFROM DailyRev\nORDER BY transaction_date;"},
        {"title": "24. 상품별 상위 2명의 큰손 고객 찾기", "difficulty": "고급", "question": "transactions 테이블을 사용하여 각 상품(product_name)별로 누적 지출(revenue)이 가장 큰 고객(user_id) 상위 2명을 뽑고자 합니다. 상품명, 고객 아이디, 결제 총액을 구한 뒤 상품명 오름차순, 결제액 내림차순으로 정렬하여 조회하세요.", "hint": "상품-유저별 합계를 구한 후, 윈도우 함수 ROW_NUMBER를 파티션(상품) 단위로 적용하여 2순위까지만 필터링하세요.", "answer": "WITH UserProductRev AS (\n    SELECT product_name, user_id, SUM(revenue) as total_rev\n    FROM transactions\n    GROUP BY product_name, user_id\n), RankedRev AS (\n    SELECT product_name, user_id, total_rev,\n           ROW_NUMBER() OVER(PARTITION BY product_name ORDER BY total_rev DESC) as rnk\n    FROM UserProductRev\n)\nSELECT product_name, user_id, total_rev\nFROM RankedRev\nWHERE rnk <= 2\nORDER BY product_name ASC, total_rev DESC;"},
        {"title": "25. 세션 이탈 후 재방문까지 걸린 평균 시간", "difficulty": "고급", "question": "유저들이 첫 번째 세션을 마친 후 두 번째 세션을 시작하기까지 며칠이 걸리는지 그 평균(days)을 구하려고 합니다. 유저별로 첫 번째 세션 날짜와 두 번째 세션 날짜의 차이를 구한 뒤, 전체 유저의 평균 일수를 'avg_days_to_return' 컬럼으로 구하세요. (세션이 1번뿐인 유저는 제외합니다.)", "hint": "두 날짜의 차이를 구하는 함수(문법에 따라 다름)를 사용하세요. 먼저 각 유저의 1, 2번째 세션을 분리하는 것이 핵심입니다.", "answer": "WITH SessionRank AS (\n    SELECT user_id, session_date,\n           ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY session_datetime ASC) as rn\n    FROM ga_sessions\n), FirstSecond AS (\n    SELECT user_id,\n           MAX(CASE WHEN rn = 1 THEN session_date END) as first_date,\n           MAX(CASE WHEN rn = 2 THEN session_date END) as second_date\n    FROM SessionRank\n    WHERE rn <= 2\n    GROUP BY user_id\n    HAVING COUNT(*) = 2\n)\nSELECT AVG(CAST(JULIANDAY(second_date) - JULIANDAY(first_date) AS INTEGER)) as avg_days_to_return\nFROM FirstSecond;"},
        {"title": "26. 특정 상품의 장바구니->구매 전환율", "difficulty": "고급", "question": "상품 구매 전환율(Conversion Rate)을 분석하기 위해, 특정 상품(product_name='Sneakers')이 장바구니('add_to_cart')에 담긴 세션 중에서 실제로 구매('purchase')까지 이어진 세션의 비율(%)을 구하세요. (힌트: events와 transactions 테이블을 연결할 수 있는 키는 session_id입니다.)", "hint": "Sneakers를 장바구니에 담은 세션을 서브쿼리로 구하고, 그 세션들이 transactions 테이블에 구매 기록이 있는지 비교하여 비율을 계산하세요.", "answer": "WITH CartSessions AS (\n    SELECT DISTINCT session_id\n    FROM ga_events e\n    JOIN transactions t ON e.session_id = t.session_id\n    WHERE e.event_name = 'add_to_cart' AND t.product_name = 'Sneakers'\n), PurchaseSessions AS (\n    SELECT DISTINCT session_id\n    FROM ga_events\n    WHERE event_name = 'purchase'\n)\nSELECT \n    CAST((SELECT COUNT(*) FROM CartSessions c JOIN PurchaseSessions p ON c.session_id = p.session_id) AS FLOAT) \n    / (SELECT COUNT(*) FROM CartSessions) * 100 as conversion_rate;"},
        {"title": "27. 첫 방문과 결제일의 차이 분석", "difficulty": "고급", "question": "고객(user_id)별로 해당 쇼핑몰에 최초로 방문(session)한 날짜와 최초로 결제(transaction)한 날짜 사이의 일수 차이를 구하고, 전체 고객의 평균 소요 일수(days)를 계산하세요.", "hint": "각 고객의 MIN(session_date)와 MIN(transaction_date)를 각각 CTE로 구한 후 조인하여 차이의 평균을 구하세요.", "answer": "WITH FirstSession AS (\n    SELECT user_id, MIN(session_date) as first_visit\n    FROM ga_sessions\n    GROUP BY user_id\n), FirstPurchase AS (\n    SELECT user_id, MIN(transaction_date) as first_purchase\n    FROM transactions\n    GROUP BY user_id\n)\nSELECT AVG(CAST(JULIANDAY(p.first_purchase) - JULIANDAY(s.first_visit) AS INTEGER)) as avg_days_to_purchase\nFROM FirstSession s\nJOIN FirstPurchase p ON s.user_id = p.user_id;"},
        {"title": "28. 가장 큰 전환을 이끌어낸 트래픽 소스", "difficulty": "고급", "question": "ga_sessions와 transactions 테이블을 조인하여, 단순 방문수 대비 실제 결제 세션 수의 비율(전환율)이 가장 높은 트래픽 소스(source)를 찾으세요. 단, 방문수가 최소 5번 이상인 소스만 대상으로 합니다.", "hint": "각 소스별 (결제 세션 수 / 전체 세션 수)를 FLOAT으로 계산하여 정렬합니다.", "answer": "WITH SessionCounts AS (\n    SELECT source, COUNT(*) as total_sessions\n    FROM ga_sessions\n    GROUP BY source\n    HAVING COUNT(*) >= 5\n), PurchaseCounts AS (\n    SELECT s.source, COUNT(DISTINCT t.session_id) as purchase_sessions\n    FROM ga_sessions s\n    JOIN transactions t ON s.session_id = t.session_id\n    GROUP BY s.source\n)\nSELECT s.source, \n       CAST(COALESCE(p.purchase_sessions, 0) AS FLOAT) / s.total_sessions * 100 as conversion_rate\nFROM SessionCounts s\nLEFT JOIN PurchaseCounts p ON s.source = p.source\nORDER BY conversion_rate DESC\nLIMIT 1;"},
        {"title": "29. 코호트 분석: 주차별 리텐션(재방문율) 엿보기", "difficulty": "고급", "question": "유저가 첫 방문을 한 달(YYYY-MM) 기준으로 코호트를 묶었을 때, 각 '유저-월' 코호트 안에서 전체 유저 중 동일한 달에 두 번 이상 방문한(재방문한) 유저의 수와 비율(%)을 구하세요. (첫 방문 월, 총 코호트 유저 수, 재방문 유저 수, 비율 출력)", "hint": "유저별 첫 방문 월을 구하는 CTE를 작성하고, 전체 방문 기록과 조인하여 방문 횟수가 2 이상인 유저를 집계합니다.", "answer": "WITH UserFirstMonth AS (\n    SELECT user_id, SUBSTR(MIN(session_date), 1, 7) as cohort_month\n    FROM ga_sessions\n    GROUP BY user_id\n), UserVisits AS (\n    SELECT user_id, COUNT(*) as total_visits\n    FROM ga_sessions\n    GROUP BY user_id\n)\nSELECT c.cohort_month, \n       COUNT(c.user_id) as total_users, \n       SUM(CASE WHEN v.total_visits >= 2 THEN 1 ELSE 0 END) as retained_users,\n       CAST(SUM(CASE WHEN v.total_visits >= 2 THEN 1 ELSE 0 END) AS FLOAT) / COUNT(c.user_id) * 100 as retention_rate\nFROM UserFirstMonth c\nJOIN UserVisits v ON c.user_id = v.user_id\nGROUP BY c.cohort_month;"},
        {"title": "30. 매출 기여도 상위 10% 고객의 매출 비중", "difficulty": "고급", "question": "전체 결제 고객 중에서 누적 지출액 기준 상위 10% 안에 드는 고객들이 발생시킨 총 매출이 전체 매출의 몇 퍼센트를 차지하는지 계산하세요.", "hint": "고객별 총 지출액과 백분위수 랭크(NTILE 또는 PERCENT_RANK 대용 로직)를 구한 뒤 상위 10%를 분리하여 합계를 구하세요.", "answer": "WITH UserRev AS (\n    SELECT user_id, SUM(revenue) as total_rev\n    FROM transactions\n    GROUP BY user_id\n), RankedUsers AS (\n    SELECT user_id, total_rev, \n           CUME_DIST() OVER(ORDER BY total_rev DESC) as percentile\n    FROM UserRev\n)\nSELECT \n    (SELECT SUM(total_rev) FROM RankedUsers WHERE percentile <= 0.1) / (SELECT SUM(total_rev) FROM RankedUsers) * 100 as top_10_revenue_pct;"}
    ],
    
    "일반 쇼핑몰 (이커머스)": [
        # 초급 (10문제)
        {"title": "1. 가장 비싼 상품 조회", "difficulty": "초급", "question": "products 테이블에서 가격(price)이 가장 높은 상품의 이름(product_name)과 가격을 조회하세요.", "hint": "ORDER BY 문을 사용하여 price를 내림차순 정렬한 뒤 가장 위에 있는 1건을 조회하세요.", "answer": "SELECT product_name, price\nFROM products\nORDER BY price DESC\nLIMIT 1;"},
        {"title": "2. VIP 고객 찾기", "difficulty": "초급", "question": "customers 테이블에서 등급(grade)이 'VIP'인 고객의 수를 조회하세요.", "hint": "WHERE 조건에 등급을 입력하고 COUNT를 사용하세요.", "answer": "SELECT COUNT(*) as vip_count\nFROM customers\nWHERE grade = 'VIP';"},
        {"title": "3. 특정 카테고리 상품 목록", "difficulty": "초급", "question": "products 테이블에서 카테고리(category)가 'Electronics'인 상품들의 이름을 조회하세요.", "hint": "WHERE 조건절을 사용하여 특정 카테고리만 필터링합니다.", "answer": "SELECT product_name\nFROM products\nWHERE category = 'Electronics';"},
        {"title": "4. Home 카테고리 상품 평균가", "difficulty": "초급", "question": "products 테이블에서 'Home' 카테고리 상품들의 평균 가격(price)을 조회하세요.", "hint": "카테고리를 제한한 뒤 AVG() 함수를 적용하세요.", "answer": "SELECT AVG(price) as avg_price\nFROM products\nWHERE category = 'Home';"},
        {"title": "5. 특정 주문의 구매 품목 수", "difficulty": "초급", "question": "order_items 테이블에서 'ORD_0001' 주문에 포함된 상세 아이템(item_id)의 개수를 조회하세요.", "hint": "특정 주문 번호로 WHERE 조건을 걸고 개수를 셉니다.", "answer": "SELECT COUNT(*) as item_count\nFROM order_items\nWHERE order_id = 'ORD_0001';"},
        {"title": "6. 전체 상품 개수 파악", "difficulty": "초급", "question": "products 테이블에 등록된 고유한 상품들의 총 개수를 구하세요.", "hint": "단순히 테이블의 행(Row) 개수를 세면 됩니다.", "answer": "SELECT COUNT(*) as total_products\nFROM products;"},
        {"title": "7. 최근 가입자 조회", "difficulty": "초급", "question": "customers 테이블에서 최근 5명의 가입자를 가입일자(join_date) 내림차순으로 조회하세요.", "hint": "ORDER BY와 DESC, 그리고 LIMIT 5를 사용하세요.", "answer": "SELECT customer_name, join_date\nFROM customers\nORDER BY join_date DESC\nLIMIT 5;"},
        {"title": "8. 특정 가격 이하의 상품 검색", "difficulty": "초급", "question": "products 테이블에서 가격(price)이 20,000원 이하인 상품들의 이름과 가격을 조회하세요.", "hint": "WHERE 절의 조건으로 부등호를 사용하세요.", "answer": "SELECT product_name, price\nFROM products\nWHERE price <= 20000;"},
        {"title": "9. 특정 등급이 아닌 고객", "difficulty": "초급", "question": "customers 테이블에서 등급(grade)이 'Bronze'가 아닌 고객의 이름(customer_name)을 모두 조회하세요.", "hint": "WHERE 조건에서 '!=' 또는 '<>' 연산자를 사용하세요.", "answer": "SELECT customer_name\nFROM customers\nWHERE grade != 'Bronze';"},
        {"title": "10. 가장 먼저 가입한 고객", "difficulty": "초급", "question": "customers 테이블에서 가장 일찍 가입한 고객의 이름과 가입일자를 조회하세요.", "hint": "join_date를 오름차순 정렬하여 1명만 가져오세요.", "answer": "SELECT customer_name, join_date\nFROM customers\nORDER BY join_date ASC\nLIMIT 1;"},

        # 중급 (10문제)
        {"title": "11. 주문별 결제 금액 산출", "difficulty": "중급", "question": "order_items 테이블을 사용하여 각 주문(order_id)별로 결제해야 할 총 금액(price * quantity)을 구하고, 상위 5개만 조회하세요.", "hint": "order_id로 GROUP BY 하고 SUM() 연산을 활용하세요.", "answer": "SELECT order_id, SUM(price * quantity) as total_amount\nFROM order_items\nGROUP BY order_id\nORDER BY total_amount DESC\nLIMIT 5;"},
        {"title": "12. 가장 많이 팔린 상품 찾기", "difficulty": "중급", "question": "order_items와 products 테이블을 조인하여, 가장 많은 수량(quantity)이 판매된 상품의 이름과 총 판매 수량을 조회하세요.", "hint": "두 테이블을 product_id로 조인하고 수량 합계 기준 내림차순 정렬하세요.", "answer": "SELECT p.product_name, SUM(oi.quantity) as total_sold\nFROM order_items oi\nJOIN products p ON oi.product_id = p.product_id\nGROUP BY p.product_name\nORDER BY total_sold DESC\nLIMIT 1;"},
        {"title": "13. 카테고리별 상품 개수", "difficulty": "중급", "question": "products 테이블에서 카테고리(category)별로 몇 개의 상품이 있는지 조회하고 많은 순으로 정렬하세요.", "hint": "GROUP BY category를 사용하고 COUNT(*) 기준으로 정렬합니다.", "answer": "SELECT category, COUNT(*) as product_count\nFROM products\nGROUP BY category\nORDER BY product_count DESC;"},
        {"title": "14. 한 번도 주문되지 않은 상품 확인", "difficulty": "중급", "question": "products와 order_items 테이블을 참조하여, 한 번도 판매된 적 없는 상품의 이름을 조회하세요.", "hint": "LEFT JOIN을 수행하고 우측 테이블(order_items)의 키가 NULL인 레코드만 필터링하세요.", "answer": "SELECT p.product_name\nFROM products p\nLEFT JOIN order_items oi ON p.product_id = oi.product_id\nWHERE oi.order_id IS NULL;"},
        {"title": "15. 고객 등급별 총 회원수", "difficulty": "중급", "question": "customers 테이블에서 등급(grade)별 회원 수를 조회하세요.", "hint": "grade 기준으로 GROUP BY 후 COUNT(*)를 사용하세요.", "answer": "SELECT grade, COUNT(*) as customer_count\nFROM customers\nGROUP BY grade;"},
        {"title": "16. 평균 이상 가격의 상품들", "difficulty": "중급", "question": "products 테이블에서 전체 상품의 평균 가격보다 높은 가격을 가진 상품들의 이름과 가격을 조회하세요.", "hint": "전체 평균을 구하는 서브쿼리 `(SELECT AVG(...) ...)`를 WHERE 절에 비교값으로 사용하세요.", "answer": "SELECT product_name, price\nFROM products\nWHERE price > (SELECT AVG(price) FROM products);"},
        {"title": "17. 다량 구매 주문 확인", "difficulty": "중급", "question": "order_items 테이블에서 한 주문(order_id) 안에 총 상품(quantity)을 5개 이상 구매한 주문 번호를 조회하세요.", "hint": "order_id로 그룹핑하고, HAVING 절을 사용해 누적 수량이 5 이상인지 확인하세요.", "answer": "SELECT order_id\nFROM order_items\nGROUP BY order_id\nHAVING SUM(quantity) >= 5;"},
        {"title": "18. 연도별 가입자 수 추이", "difficulty": "중급", "question": "customers 테이블에서 연도(join_date의 앞 4자리)별로 몇 명이 가입했는지 조회하세요.", "hint": "문자열 조작 함수를 활용하여 연도만 추출한 뒤 그룹화하세요.", "answer": "SELECT SUBSTR(join_date, 1, 4) as join_year, COUNT(*) as users\nFROM customers\nGROUP BY SUBSTR(join_date, 1, 4);"},
        {"title": "19. 고객별 주문 횟수 랭킹", "difficulty": "중급", "question": "orders 테이블에서 각 고객(customer_id)별 총 주문 횟수를 구하고 가장 주문을 많이 한 상위 3명의 고객 ID를 조회하세요.", "hint": "GROUP BY 와 ORDER BY를 적절히 섞어 사용하세요.", "answer": "SELECT customer_id, COUNT(*) as order_count\nFROM orders\nGROUP BY customer_id\nORDER BY order_count DESC\nLIMIT 3;"},
        {"title": "20. 특정 기간 집중 구매자 필터링", "difficulty": "중급", "question": "orders 테이블에서 '2023-12'월에 주문을 2회 이상 발생시킨 고객(customer_id)을 조회하세요.", "hint": "날짜 필터링을 한 후 그룹화 및 HAVING 조건절을 적용하세요.", "answer": "SELECT customer_id\nFROM orders\nWHERE order_date LIKE '2023-12%'\nGROUP BY customer_id\nHAVING COUNT(*) >= 2;"},

        # 고급 (10문제)
        {"title": "21. 3개월 연속 구매 고객 찾기", "difficulty": "고급", "question": "충성 고객을 분류하기 위해, orders 테이블을 참조하여 서로 다른 3개월 동안 최소 한 번씩 주문을 완료한 고객(customer_id)을 찾으려고 합니다. 이 조건을 만족하는 고객의 아이디를 모두 구하세요.", "hint": "먼저 고객별로 주문한 '연-월'(문자열 자르기) 중복을 제거한 서브쿼리를 만들고, 그룹핑으로 개수가 3개 이상인 고객을 찾으세요.", "answer": "WITH MonthlyOrders AS (\n    SELECT DISTINCT customer_id, SUBSTR(order_date, 1, 7) as order_month\n    FROM orders\n)\nSELECT customer_id\nFROM MonthlyOrders\nGROUP BY customer_id\nHAVING COUNT(order_month) >= 3;"},
        {"title": "22. 각 카테고리 내 매출 1위 상품 구하기", "difficulty": "고급", "question": "products 테이블과 order_items 테이블을 조인하여, 각 카테고리(category) 내에서 매출액(price * quantity 합산)이 가장 높은 1위 상품의 카테고리명, 상품명, 총 매출액을 추출하세요.", "hint": "각 상품별 총 매출을 먼저 구한 뒤, 윈도우 함수 ROW_NUMBER를 사용하여 그룹(카테고리) 단위로 1순위만 필터링합니다.", "answer": "WITH ProductRevenue AS (\n    SELECT p.category, p.product_name, SUM(oi.price * oi.quantity) as total_rev\n    FROM products p\n    JOIN order_items oi ON p.product_id = oi.product_id\n    GROUP BY p.category, p.product_name\n), RankedCategory AS (\n    SELECT category, product_name, total_rev,\n           ROW_NUMBER() OVER(PARTITION BY category ORDER BY total_rev DESC) as rnk\n    FROM ProductRevenue\n)\nSELECT category, product_name, total_rev\nFROM RankedCategory\nWHERE rnk = 1;"},
        {"title": "23. 장바구니 분석(연관 상품 찾기)", "difficulty": "고급", "question": "'Product 1'을 구매한 사람들이 함께 주문한 다른 상품들을 분석하려고 합니다. order_items 테이블 안에서 'Product 1'이 포함된 같은 주문(order_id) 안에서 함께 구매된 다른 상품들의 아이디(product_id)와 횟수(함께 구매된 횟수)를 내림차순으로 구하세요.", "hint": "order_items 테이블을 스스로(Self) JOIN하여 한 쪽은 'Product 1', 다른 쪽은 그 외 상품이 되도록 구성하세요.", "answer": "SELECT o2.product_id as companion_product, COUNT(*) as co_occurrence\nFROM order_items o1\nJOIN order_items o2 ON o1.order_id = o2.order_id\nWHERE o1.product_id = 'P_001' AND o2.product_id != 'P_001'\nGROUP BY o2.product_id\nORDER BY co_occurrence DESC;"},
        {"title": "24. 고객 등급별 총 지출 및 평균 지출 기여도", "difficulty": "고급", "question": "customers, orders, order_items 세 테이블을 합쳐서, 고객의 등급(grade)별로 발생한 '총 결제 금액 합계'와 전체 매출액 대비 해당 등급이 차지하는 '기여도 비율(퍼센트)'을 조회하세요.", "hint": "우선 등급별 총합을 구하는 서브쿼리/CTE를 만듭니다. 기여도는 (각 등급 총합 / 전체 총합) * 100 으로 계산합니다.", "answer": "WITH GradeRevenue AS (\n    SELECT c.grade, SUM(oi.price * oi.quantity) as total_rev\n    FROM customers c\n    JOIN orders o ON c.customer_id = o.customer_id\n    JOIN order_items oi ON o.order_id = oi.order_id\n    GROUP BY c.grade\n)\nSELECT grade, total_rev,\n       CAST(total_rev AS FLOAT) / (SELECT SUM(total_rev) FROM GradeRevenue) * 100 as contribution_pct\nFROM GradeRevenue;"},
        {"title": "25. 첫 구매와 마지막 구매 사이의 총 일수", "difficulty": "고급", "question": "고객(customer_id)별로 발생시킨 가장 첫 번째 주문 날짜와 가장 최근(마지막) 주문 날짜를 구하고, 두 주문 사이의 경과 일수(days)를 계산하세요. 단, 한 번만 구매한 고객은 제외해야 합니다.", "hint": "MIN()과 MAX()로 날짜를 구한 뒤 날짜 차이를 구하는 함수를 활용하여 0보다 큰 결과만 반환하세요.", "answer": "WITH CustomerDates AS (\n    SELECT customer_id, \n           MIN(order_date) as first_order,\n           MAX(order_date) as last_order\n    FROM orders\n    GROUP BY customer_id\n)\nSELECT customer_id, first_order, last_order,\n       CAST(JULIANDAY(last_order) - JULIANDAY(first_order) AS INTEGER) as days_between\nFROM CustomerDates\nWHERE CAST(JULIANDAY(last_order) - JULIANDAY(first_order) AS INTEGER) > 0;"},
        {"title": "26. 특정 상품군의 동시 이탈률 (연관 구매 분석)", "difficulty": "고급", "question": "주문에 'Clothing' 카테고리 상품이 포함되어 있을 때, 해당 주문이 다른 카테고리 상품도 1개 이상 포함하고 있는지(교차 구매 여부) 조사하고 싶습니다. 'Clothing' 카테고리를 포함한 모든 주문 중에서 다른 카테고리도 포함한 주문의 비율(%)을 구하세요.", "hint": "주문(order_id)별로 어떤 카테고리들을 샀는지 서브쿼리로 파악하고 비율을 계산하세요.", "answer": "WITH OrderCategories AS (\n    SELECT oi.order_id, p.category\n    FROM order_items oi\n    JOIN products p ON oi.product_id = p.product_id\n), ClothingOrders AS (\n    SELECT DISTINCT order_id\n    FROM OrderCategories\n    WHERE category = 'Clothing'\n), CrossBuyOrders AS (\n    SELECT DISTINCT o.order_id\n    FROM OrderCategories o\n    JOIN ClothingOrders c ON o.order_id = c.order_id\n    WHERE o.category != 'Clothing'\n)\nSELECT \n    CAST((SELECT COUNT(*) FROM CrossBuyOrders) AS FLOAT) / \n    (SELECT COUNT(*) FROM ClothingOrders) * 100 as cross_buy_ratio;"},
        {"title": "27. RFM 세그먼테이션: Recency 기준 정렬", "difficulty": "고급", "question": "고객 가치 평가(RFM)를 위해, 고객(customer_id)별로 가장 최근 구매일(MAX order_date)을 구한 뒤 가장 구매를 최근에 한 사람부터 내림차순 정렬하여 상위 10명을 조회하세요. 고객 이름(customer_name)도 포함되어야 합니다.", "hint": "orders 테이블에서 그룹별 MAX(order_date)를 구한 뒤 customers와 JOIN 하세요.", "answer": "WITH CustomerRecent AS (\n    SELECT customer_id, MAX(order_date) as recent_order\n    FROM orders\n    GROUP BY customer_id\n)\nSELECT c.customer_name, r.recent_order\nFROM CustomerRecent r\nJOIN customers c ON r.customer_id = c.customer_id\nORDER BY r.recent_order DESC\nLIMIT 10;"},
        {"title": "28. 취소된 적 없는 상품 필터링 (가상 시나리오)", "difficulty": "고급", "question": "현재 취소 상태 컬럼이 없지만 응용 쿼리입니다. 모든 주문이 완료되었다고 가정할 때, 구매 수량(quantity)이 3개 미만인 적이 단 한 번도 없는(즉 샀다 하면 항상 3개 이상만 산) 상품들의 이름을 추출하세요.", "hint": "product_id 기준으로 MIN(quantity)를 구하고 그 값이 3 이상인 상품만 찾으세요.", "answer": "WITH ProductMinQty AS (\n    SELECT product_id, MIN(quantity) as min_qty\n    FROM order_items\n    GROUP BY product_id\n)\nSELECT p.product_name\nFROM ProductMinQty m\nJOIN products p ON m.product_id = p.product_id\nWHERE m.min_qty >= 3;"},
        {"title": "29. 주문 객단가(AOV)가 가장 높은 날짜 찾기", "difficulty": "고급", "question": "하루에 일어난 총 매출(총 결제 금액)을 그 날 발생한 총 주문 건수로 나눈 값인 '객단가(Average Order Value)'를 일자(order_date)별로 구하고 가장 객단가가 높은 날짜를 조회하세요.", "hint": "일자별 총 매출과 고유 주문(order_id) 건수를 구하는 집계 서브쿼리를 활용하세요.", "answer": "WITH DailyOrders AS (\n    SELECT o.order_date, \n           COUNT(DISTINCT o.order_id) as total_orders,\n           SUM(oi.price * oi.quantity) as total_revenue\n    FROM orders o\n    JOIN order_items oi ON o.order_id = oi.order_id\n    GROUP BY o.order_date\n)\nSELECT order_date, \n       CAST(total_revenue AS FLOAT) / total_orders as aov\nFROM DailyOrders\nORDER BY aov DESC\nLIMIT 1;"},
        {"title": "30. 누적 지출액 100만원 이상 돌파 고객", "difficulty": "고급", "question": "시간이 지남에 따라 고객이 각 주문에서 지출한 금액을 누적하여 합산합니다. 각 고객이 최초로 누적 지출 1,000,000을 넘긴 시점(order_id와 누적 금액)을 구하세요.", "hint": "윈도우 함수 SUM() OVER(PARTITION BY customer_id ORDER BY order_date)를 사용하여 각 주문 시점의 누적액을 계산한 뒤 필터링합니다.", "answer": "WITH CumulativeSpend AS (\n    SELECT o.customer_id, o.order_id, o.order_date,\n           SUM(oi.price * oi.quantity) as order_amount,\n           SUM(SUM(oi.price * oi.quantity)) OVER(PARTITION BY o.customer_id ORDER BY o.order_date ASC) as running_total\n    FROM orders o\n    JOIN order_items oi ON o.order_id = oi.order_id\n    GROUP BY o.customer_id, o.order_id, o.order_date\n)\nSELECT customer_id, order_id, running_total\nFROM CumulativeSpend\nWHERE running_total >= 1000000\nGROUP BY customer_id; -- 첫 돌파 시점만"}
    ],
    
    "금융/은행 (Finance)": [
        # 초급 (10문제)
        {"title": "1. 잔액이 가장 많은 계좌", "difficulty": "초급", "question": "accounts 테이블에서 현재 잔액(balance)이 가장 많은 상위 3개의 account_id와 balance를 조회하세요.", "hint": "ORDER BY DESC 및 LIMIT를 이용하세요.", "answer": "SELECT account_id, balance\nFROM accounts\nORDER BY balance DESC\nLIMIT 3;"},
        {"title": "2. 특정 고객의 계좌 수", "difficulty": "초급", "question": "accounts 테이블에서 'CUST_001' 고객이 보유한 계좌의 총 개수를 구하세요.", "hint": "WHERE 조건절로 customer_id를 필터링 후 COUNT를 사용하세요.", "answer": "SELECT COUNT(*) as account_count\nFROM accounts\nWHERE customer_id = 'CUST_001';"},
        {"title": "3. 신용 점수 800 이상인 고객", "difficulty": "초급", "question": "customers 테이블에서 신용 점수(credit_score)가 800 이상인 고객의 이름(customer_name)을 조회하세요.", "hint": "WHERE 조건식(>=)을 사용하세요.", "answer": "SELECT customer_name\nFROM customers\nWHERE credit_score >= 800;"},
        {"title": "4. 모든 대출의 평균 이자율", "difficulty": "초급", "question": "loans 테이블에 등록된 모든 대출 상품의 평균 이자율(interest_rate)을 조회하세요.", "hint": "AVG() 함수를 사용하세요.", "answer": "SELECT AVG(interest_rate) as avg_interest_rate\nFROM loans;"},
        {"title": "5. 특정 계좌의 인출 내역 건수", "difficulty": "초급", "question": "transactions 테이블에서 거래 유형이 'WITHDRAWAL'인 거래가 총 몇 번 일어났는지 조회하세요.", "hint": "WHERE 조건식으로 'WITHDRAWAL'을 필터링하세요.", "answer": "SELECT COUNT(*) as withdrawal_count\nFROM transactions\nWHERE transaction_type = 'WITHDRAWAL';"},
        {"title": "6. SAVINGS 계좌 목록", "difficulty": "초급", "question": "accounts 테이블에서 계좌 종류(account_type)가 'SAVINGS'인 계좌들의 번호를 조회하세요.", "hint": "문자열 필터링을 사용하세요.", "answer": "SELECT account_id\nFROM accounts\nWHERE account_type = 'SAVINGS';"},
        {"title": "7. 대출 잔액 가장 적은 고객", "difficulty": "초급", "question": "loans 테이블에서 대출 금액(loan_amount)이 가장 적은 대출건의 아이디와 대출 금액을 조회하세요.", "hint": "ORDER BY ASC 정렬 후 LIMIT를 적용하세요.", "answer": "SELECT loan_id, loan_amount\nFROM loans\nORDER BY loan_amount ASC\nLIMIT 1;"},
        {"title": "8. 신용 점수 미달 고객", "difficulty": "초급", "question": "customers 테이블에서 신용 점수(credit_score)가 500점 미만인 고객들의 이름을 조회하세요.", "hint": "조건절에서 부등호(<)를 활용하세요.", "answer": "SELECT customer_name\nFROM customers\nWHERE credit_score < 500;"},
        {"title": "9. 특정 날짜의 거래 내역", "difficulty": "초급", "question": "transactions 테이블에서 '2023-01-15'일에 발생한 모든 거래를 조회하세요.", "hint": "날짜 문자열을 매칭시키세요 (LIKE가 유용할 수 있습니다).", "answer": "SELECT *\nFROM transactions\nWHERE transaction_date LIKE '2023-01-15%';"},
        {"title": "10. 총 예치금 확인", "difficulty": "초급", "question": "accounts 테이블에 존재하는 모든 계좌의 잔액(balance) 총합을 구하세요.", "hint": "전체 레코드에 대해 SUM()을 적용하세요.", "answer": "SELECT SUM(balance) as total_bank_balance\nFROM accounts;"},
        
        # 중급 (10문제)
        {"title": "11. 거래 유형별 총 금액", "difficulty": "중급", "question": "transactions 테이블에서 거래 유형(transaction_type)별 총 금액(amount) 합계를 조회하세요.", "hint": "transaction_type으로 GROUP BY 한 후 합계를 계산하세요.", "answer": "SELECT transaction_type, SUM(amount) as total_amount\nFROM transactions\nGROUP BY transaction_type;"},
        {"title": "12. 입금 내역 집계", "difficulty": "중급", "question": "transactions 테이블에서 거래 유형이 'DEPOSIT'(입금)인 거래들의 계좌(account_id)별 총 입금액을 구하세요.", "hint": "WHERE 절에서 'DEPOSIT'을 걸러내고 그룹화하세요.", "answer": "SELECT account_id, SUM(amount) as total_deposit\nFROM transactions\nWHERE transaction_type = 'DEPOSIT'\nGROUP BY account_id\nORDER BY total_deposit DESC;"},
        {"title": "13. VIP 고객 대출 내역 확인", "difficulty": "중급", "question": "customers와 loans 테이블을 조인하여, 신용 점수(credit_score)가 800점 이상인 고객들의 고객명(customer_name)과 대출 잔액(loan_amount)을 조회하세요.", "hint": "두 테이블을 조인하고 WHERE로 신용 점수 조건을 추가하세요.", "answer": "SELECT c.customer_name, l.loan_amount\nFROM customers c\nJOIN loans l ON c.customer_id = l.customer_id\nWHERE c.credit_score >= 800;"},
        {"title": "14. 평균 잔액 이하인 계좌", "difficulty": "중급", "question": "accounts 테이블에서 전체 계좌의 평균 잔액보다 잔액(balance)이 적은 계좌 번호(account_id)를 조회하세요.", "hint": "WHERE 절의 조건으로 평균을 구하는 서브쿼리를 사용하세요.", "answer": "SELECT account_id\nFROM accounts\nWHERE balance < (SELECT AVG(balance) FROM accounts);"},
        {"title": "15. 이자율이 가장 높은 대출", "difficulty": "중급", "question": "loans 테이블에서 이자율(interest_rate)이 가장 높은 대출건의 loan_id와 이자율을 조회하세요.", "hint": "ORDER BY 문으로 내림차순 정렬 후 최상단 1개만 조회합니다.", "answer": "SELECT loan_id, interest_rate\nFROM loans\nORDER BY interest_rate DESC\nLIMIT 1;"},
        {"title": "16. 고객별 계좌 잔액 합계", "difficulty": "중급", "question": "accounts 테이블을 사용하여, 고객(customer_id)별 총 계좌 잔액 합계를 구하고 높은 순으로 5명 조회하세요.", "hint": "그룹핑하고 SUM 연산 후 내림차순 정렬을 적용하세요.", "answer": "SELECT customer_id, SUM(balance) as total_balance\nFROM accounts\nGROUP BY customer_id\nORDER BY total_balance DESC\nLIMIT 5;"},
        {"title": "17. 특정 거래 일자의 입출금 건수", "difficulty": "중급", "question": "transactions 테이블에서 '2023-01'월에 발생한 모든 거래의 횟수를 구하세요.", "hint": "LIKE 연산자를 활용하여 문자열 기반 검색을 하세요.", "answer": "SELECT COUNT(*) as txn_count\nFROM transactions\nWHERE transaction_date LIKE '2023-01%';"},
        {"title": "18. 계좌 종류별 평균 잔액", "difficulty": "중급", "question": "accounts 테이블에서 계좌 종류(account_type)별 평균 잔액을 조회하세요.", "hint": "account_type으로 그룹핑한 뒤 평균 함수를 사용하세요.", "answer": "SELECT account_type, AVG(balance) as avg_balance\nFROM accounts\nGROUP BY account_type;"},
        {"title": "19. 대출이 있는 고객 수", "difficulty": "중급", "question": "loans 테이블에 등록된 대출을 하나라도 보유하고 있는 고유한 고객(customer_id)이 몇 명인지 조회하세요.", "hint": "중복을 제거하는 DISTINCT 키워드를 카운트 내부에 사용하세요.", "answer": "SELECT COUNT(DISTINCT customer_id) as loan_customers\nFROM loans;"},
        {"title": "20. 신규 대출 및 고이자 대출 필터", "difficulty": "중급", "question": "loans 테이블에서 대출 금액이 50,000을 넘거나 이자율이 15%를 초과하는 대출 번호를 모두 조회하세요.", "hint": "WHERE 조건절에서 OR 논리 연산자를 사용하세요.", "answer": "SELECT loan_id\nFROM loans\nWHERE loan_amount > 50000 OR interest_rate > 15;"},
        
        # 고급 (10문제)
        {"title": "21. 이상 징후: 잔고를 초과한 대량 인출", "difficulty": "고급", "question": "transactions 테이블과 accounts 테이블을 활용하여 거래 유형이 'WITHDRAWAL'(인출)이면서 동시에 그 인출 금액이 계좌의 현재 잔고(balance)를 초과하는 비정상 거래들의 내역(transaction_id, account_id, amount, balance)을 모두 조회하세요.", "hint": "두 테이블을 조인한 상태에서 WHERE 절에 두 가지 조건(인출 여부 AND amount > balance)을 동시에 작성하세요.", "answer": "SELECT t.transaction_id, t.account_id, t.amount, a.balance\nFROM transactions t\nJOIN accounts a ON t.account_id = a.account_id\nWHERE t.transaction_type = 'WITHDRAWAL' AND t.amount > a.balance;"},
        {"title": "22. 고객 자산 건전성 검사 (순자산 마이너스)", "difficulty": "고급", "question": "자산 건전성을 파악하기 위해 고객별 총 예금 자산과 총 대출 부채를 비교해야 합니다. '모든 계좌의 잔고 합계'보다 '빌린 대출 금액의 합계'가 더 큰(즉, 순자산이 마이너스인) 고객들의 아이디(customer_id)를 추출하세요.", "hint": "accounts 그룹합계, loans 그룹합계를 구하는 서브쿼리를 만들고 조인하여 비교하세요.", "answer": "SELECT c.customer_id\nFROM customers c\nJOIN (SELECT customer_id, SUM(balance) as total_bal FROM accounts GROUP BY customer_id) a ON c.customer_id = a.customer_id\nJOIN (SELECT customer_id, SUM(loan_amount) as total_loan FROM loans GROUP BY customer_id) l ON c.customer_id = l.customer_id\nWHERE l.total_loan > a.total_bal;"},
        {"title": "23. 계좌 입출금 누적 잔액 시뮬레이션", "difficulty": "고급", "question": "특정 계좌('ACC_0001')의 거래 내역을 시간순으로 정렬하고, 매 거래가 일어날 때마다 변동되는 순수익(DEPOSIT은 양수, WITHDRAWAL은 음수 처리)의 누적합(Running Total)을 구하여 시간에 따른 계좌 잔액 흐름을 시뮬레이션 하세요.", "hint": "CASE WHEN 구문으로 입출금 부호를 다르게 변환하고, 윈도우 함수를 사용하여 누적합을 만듭니다.", "answer": "SELECT transaction_id, transaction_date, transaction_type, amount,\n       SUM(CASE WHEN transaction_type = 'DEPOSIT' THEN amount \n                WHEN transaction_type = 'WITHDRAWAL' THEN -amount ELSE 0 END)\n       OVER(ORDER BY transaction_date ASC) as running_balance\nFROM transactions\nWHERE account_id = 'ACC_0001'\nORDER BY transaction_date ASC;"},
        {"title": "24. 대출이 없으면서 잔고 상위 10%인 고객", "difficulty": "고급", "question": "loans 테이블에 대출 기록이 전혀 없는 고객 중에서, 자신이 보유한 계좌들의 총 잔고 합계 기준 내림차순으로 가장 여유 자금이 많은 상위 5명을 찾아 이름(customer_name)과 총 잔액을 조회하세요.", "hint": "LEFT JOIN을 수행한 뒤 우측 테이블(대출)의 ID가 NULL인 조건을 추가하여 대출 없는 고객을 필터링 하세요.", "answer": "SELECT c.customer_name, SUM(a.balance) as total_balance\nFROM customers c\nJOIN accounts a ON c.customer_id = a.customer_id\nLEFT JOIN loans l ON c.customer_id = l.customer_id\nWHERE l.loan_id IS NULL\nGROUP BY c.customer_id, c.customer_name\nORDER BY total_balance DESC\nLIMIT 5;"},
        {"title": "25. 비활성 계좌(유령 계좌) 필터링", "difficulty": "고급", "question": "accounts 테이블에는 존재하지만 transactions 테이블에 거래 내역이 단 한 건도 없는 '비활성 계좌'를 찾아야 합니다. 거래가 전무한 계좌의 번호(account_id)와 현재 잔고(balance)를 조회하세요.", "hint": "accounts에 transactions를 LEFT JOIN하고 데이터가 없는 행을 찾거나 NOT EXISTS를 활용하세요.", "answer": "SELECT a.account_id, a.balance\nFROM accounts a\nLEFT JOIN transactions t ON a.account_id = t.account_id\nWHERE t.transaction_id IS NULL;"},
        {"title": "26. 신용등급 대비 대출 초과 위험군 추출", "difficulty": "고급", "question": "고객의 신용점수 대비 대출금액이 과도하게 높은 위험군을 파악하려 합니다. 각 고객별 '대출 총액 / 신용 점수 비율'을 구하고, 그 비율이 100(가상의 임계치)을 초과하는 고객의 ID와 이름, 비율을 내림차순으로 조회하세요.", "hint": "고객별 대출 총액을 서브쿼리로 구한 뒤 신용점수로 나누어 조건을 검사하세요.", "answer": "WITH CustomerLoans AS (\n    SELECT customer_id, SUM(loan_amount) as total_loan\n    FROM loans\n    GROUP BY customer_id\n)\nSELECT c.customer_id, c.customer_name, \n       CAST(cl.total_loan AS FLOAT) / c.credit_score as loan_to_credit_ratio\nFROM customers c\nJOIN CustomerLoans cl ON c.customer_id = cl.customer_id\nWHERE CAST(cl.total_loan AS FLOAT) / c.credit_score > 100\nORDER BY loan_to_credit_ratio DESC;"},
        {"title": "27. 연체 이자 시뮬레이션(단리 기준)", "difficulty": "고급", "question": "loans 테이블에서 현재 대출 금액(loan_amount)에 대해 1년간 이자율(interest_rate)을 단리로 적용했을 때, 1년 뒤 고객이 갚아야 할 '총 원리금(원금 + 이자)'을 계산하고 가장 많은 원리금을 갚아야 하는 대출 번호를 찾으세요.", "hint": "원금 + (원금 * 이자율 / 100) 수식을 사용하여 새로운 컬럼을 만들고 정렬하세요.", "answer": "SELECT loan_id, \n       loan_amount + (loan_amount * interest_rate / 100.0) as total_repayment\nFROM loans\nORDER BY total_repayment DESC\nLIMIT 1;"},
        {"title": "28. 가장 빈번하게 발생한 거래 계좌", "difficulty": "고급", "question": "transactions 테이블에서 하루 동안 거래가 3번 이상 발생한 '의심스러운 빈번 거래' 계좌를 탐지하려고 합니다. 거래 일자(문자열 앞 10자리)와 계좌 번호별로 그룹화하여 거래 횟수가 3회 이상인 계좌와 날짜를 조회하세요.", "hint": "날짜 문자열을 자르는 함수(SUBSTR 등)를 사용하여 연월일로 그룹화 한 후 HAVING 카운트 조건을 추가하세요.", "answer": "SELECT account_id, SUBSTR(transaction_date, 1, 10) as txn_date, COUNT(*) as daily_txns\nFROM transactions\nGROUP BY account_id, SUBSTR(transaction_date, 1, 10)\nHAVING COUNT(*) >= 3;"},
        {"title": "29. 월말 잔액 추정", "difficulty": "고급", "question": "accounts 테이블의 현재 잔고는 기말 잔고라고 가정합니다. 지난달에 발생한 입출금 변동을 역추적하기 위해 현재 잔고에서 transactions에 기록된 입금은 빼고 출금은 더해 '과거 기준 잔액'을 추정하려 합니다. 각 계좌별 역계산된 잔액을 구하세요.", "hint": "각 계좌별 순변동액을 구하는 서브쿼리를 만들고 accounts 테이블의 현재 balance에 역연산(- 변동액)을 적용합니다.", "answer": "WITH NetChange AS (\n    SELECT account_id, \n           SUM(CASE WHEN transaction_type = 'DEPOSIT' THEN amount \n                    WHEN transaction_type = 'WITHDRAWAL' THEN -amount ELSE 0 END) as net_amount\n    FROM transactions\n    GROUP BY account_id\n)\nSELECT a.account_id, a.balance, \n       a.balance - COALESCE(n.net_amount, 0) as past_balance\nFROM accounts a\nLEFT JOIN NetChange n ON a.account_id = n.account_id;"},
        {"title": "30. 고객 자산 포트폴리오 다각화 지수", "difficulty": "고급", "question": "은행은 고객이 단일 계좌(예: SAVINGS만 3개)만 가지는 것보다 여러 타입(CHECKING, SAVINGS, INVESTMENT 등)의 계좌를 고루 가지는 것을 선호합니다. 고객(customer_id)별로 보유하고 있는 고유한 계좌 종류(account_type)의 개수를 구하고, 2가지 이상의 계좌 종류를 보유한 고객만 조회하세요.", "hint": "COUNT 함수 안에 DISTINCT 속성명(account_type)을 사용하고 HAVING 절을 적용하세요.", "answer": "SELECT c.customer_id, c.customer_name, COUNT(DISTINCT a.account_type) as unique_account_types\nFROM customers c\nJOIN accounts a ON c.customer_id = a.customer_id\nGROUP BY c.customer_id, c.customer_name\nHAVING COUNT(DISTINCT a.account_type) >= 2;"}
    ]
    ,
    "스트리밍 / 콘텐츠 플랫폼": [
        # 초급 (10문제)
        {"title": "1. 미국 가입자 수 확인", "difficulty": "초급", "question": "users 테이블에서 국가(country)가 'US'인 가입자의 총 수를 조회하세요.", "hint": "WHERE 절에 국가 코드를 지정하고 COUNT()를 사용하세요.", "answer": "SELECT COUNT(*) as us_users\nFROM users\nWHERE country = 'US';"},
        {"title": "2. 최신 개봉 영화 찾기", "difficulty": "초급", "question": "content 테이블에서 2023년 이후(2023년 포함)에 개봉한 영화(type='movie')의 제목(title)과 개봉 연도를 조회하세요.", "hint": "WHERE 조건에 연도와 타입을 함께 지정하세요.", "answer": "SELECT title, release_year\nFROM content\nWHERE type = 'movie' AND release_year >= 2023;"},
        {"title": "3. 프리미엄 요금제 비율", "difficulty": "초급", "question": "users 테이블에서 각 요금제(plan_type)별 가입자 수를 조회하세요.", "hint": "plan_type으로 그룹화하고 COUNT(*)를 적용하세요.", "answer": "SELECT plan_type, COUNT(*) as user_count\nFROM users\nGROUP BY plan_type;"},
        {"title": "4. 상위 평점 콘텐츠", "difficulty": "초급", "question": "content 테이블에서 전체 평점(rating)이 9.0 이상인 콘텐츠의 제목과 평점을 내림차순 정렬하여 조회하세요.", "hint": "WHERE 평점 조건과 ORDER BY 내림차순 정렬을 함께 사용하세요.", "answer": "SELECT title, rating\nFROM content\nWHERE rating >= 9.0\nORDER BY rating DESC;"},
        {"title": "5. 코미디 장르 콘텐츠 수", "difficulty": "초급", "question": "content 테이블에서 장르(genre)가 'Comedy'인 콘텐츠가 몇 개인지 조회하세요.", "hint": "특정 장르로 필터링한 후 행의 개수를 세면 됩니다.", "answer": "SELECT COUNT(*) as comedy_count\nFROM content\nWHERE genre = 'Comedy';"},
        {"title": "6. 활성 구독자 수 파악", "difficulty": "초급", "question": "subscriptions 테이블에서 현재 구독 상태(status)가 'active'인 건수를 조회하세요.", "hint": "상태 컬럼을 조건으로 검색하세요.", "answer": "SELECT COUNT(*) as active_subs\nFROM subscriptions\nWHERE status = 'active';"},
        {"title": "7. 만점 리뷰 찾기", "difficulty": "초급", "question": "reviews 테이블에서 평점(score)을 5점 만점으로 준 리뷰 내용(comment)과 작성 시간을 조회하세요.", "hint": "score 컬럼을 기준으로 필터링하세요.", "answer": "SELECT comment, created_at\nFROM reviews\nWHERE score = 5;"},
        {"title": "8. 특정 유저의 시청 기록", "difficulty": "초급", "question": "watch_history 테이블에서 'U_0001' 유저가 시청한 기록을 최근 시청 시간(watched_at) 순으로 내림차순 정렬하여 5건 조회하세요.", "hint": "WHERE로 유저 ID를 필터링하고 ORDER BY와 LIMIT를 적용하세요.", "answer": "SELECT *\nFROM watch_history\nWHERE user_id = 'U_0001'\nORDER BY watched_at DESC\nLIMIT 5;"},
        {"title": "9. 완주한 콘텐츠 수", "difficulty": "초급", "question": "watch_history 테이블에서 끝까지 완주한(completed = 1) 시청 이력의 총 개수를 구하세요.", "hint": "completed 컬럼이 참(True 또는 1)인 조건을 사용하세요.", "answer": "SELECT COUNT(*) as completed_watches\nFROM watch_history\nWHERE completed = 1;"},
        {"title": "10. 가장 짧은 영화", "difficulty": "초급", "question": "content 테이블에서 재생 시간(duration_min)이 가장 짧은 영화(type='movie') 1개의 제목과 재생 시간을 조회하세요.", "hint": "재생 시간 오름차순 정렬 후 최상단 1개만 조회하세요.", "answer": "SELECT title, duration_min\nFROM content\nWHERE type = 'movie'\nORDER BY duration_min ASC\nLIMIT 1;"},
        
        # 중급 (10문제)
        {"title": "11. 장르별 평균 평점", "difficulty": "중급", "question": "content 테이블에서 각 장르(genre)별 평균 평점(rating)을 구하고, 평점이 높은 순으로 정렬하세요.", "hint": "GROUP BY genre와 AVG(rating)을 활용하세요.", "answer": "SELECT genre, AVG(rating) as avg_rating\nFROM content\nGROUP BY genre\nORDER BY avg_rating DESC;"},
        {"title": "12. 국가별 가입자 랭킹", "difficulty": "중급", "question": "users 테이블에서 가입자가 가장 많은 상위 3개 국가(country)와 그 수를 조회하세요.", "hint": "국가별로 묶어 COUNT를 구한 후 정렬과 LIMIT를 적용합니다.", "answer": "SELECT country, COUNT(*) as user_count\nFROM users\nGROUP BY country\nORDER BY user_count DESC\nLIMIT 3;"},
        {"title": "13. 가장 리뷰가 많은 콘텐츠", "difficulty": "중급", "question": "reviews와 content 테이블을 조인하여, 가장 많은 리뷰가 달린 콘텐츠의 제목(title)과 리뷰 개수를 조회하세요.", "hint": "content_id로 조인하고 COUNT(*) 기준으로 내림차순 정렬하세요.", "answer": "SELECT c.title, COUNT(r.review_id) as review_count\nFROM reviews r\nJOIN content c ON r.content_id = c.content_id\nGROUP BY c.title\nORDER BY review_count DESC\nLIMIT 1;"},
        {"title": "14. 월별 활성 구독 전환 수", "difficulty": "중급", "question": "subscriptions 테이블에서 상태(status)가 'active'인 구독들을 대상으로, 시작된 연-월(YYYY-MM)별 구독 건수를 조회하세요.", "hint": "문자열 자르기 함수를 사용하여 start_date의 앞 7자리를 추출하고 그룹핑하세요.", "answer": "SELECT SUBSTR(start_date, 1, 7) as sub_month, COUNT(*) as new_active_subs\nFROM subscriptions\nWHERE status = 'active'\nGROUP BY SUBSTR(start_date, 1, 7)\nORDER BY sub_month ASC;"},
        {"title": "15. 평균 시청 시간 비교", "difficulty": "중급", "question": "watch_history 테이블에서 완주한 시청 이력(completed=1)과 중도 이탈한 시청 이력(completed=0) 간의 평균 시청 시간(watched_sec)을 비교 조회하세요.", "hint": "completed 컬럼 기준으로 GROUP BY 하여 AVG()를 구하세요.", "answer": "SELECT completed, AVG(watched_sec) as avg_watch_time\nFROM watch_history\nGROUP BY completed;"},
        {"title": "16. 유저별 총 시청 시간", "difficulty": "중급", "question": "watch_history 테이블에서 각 유저(user_id)별 총 시청 시간(watched_sec)의 합을 구하고, 시청 시간이 가장 긴 상위 5명을 조회하세요.", "hint": "user_id로 그룹화하고 SUM(watched_sec)을 기준으로 정렬하세요.", "answer": "SELECT user_id, SUM(watched_sec) as total_watch_sec\nFROM watch_history\nGROUP BY user_id\nORDER BY total_watch_sec DESC\nLIMIT 5;"},
        {"title": "17. 최다 시청 콘텐츠 TOP 3", "difficulty": "중급", "question": "watch_history와 content 테이블을 조인하여, 사람들이 가장 많이 시청한(조회수가 많은) 콘텐츠 제목 상위 3개를 구하세요.", "hint": "조인 후 title로 그룹화하고 총 행의 개수(COUNT)로 랭킹을 매기세요.", "answer": "SELECT c.title, COUNT(*) as view_count\nFROM watch_history w\nJOIN content c ON w.content_id = c.content_id\nGROUP BY c.title\nORDER BY view_count DESC\nLIMIT 3;"},
        {"title": "18. 평균 평점이 가장 낮은 장르", "difficulty": "중급", "question": "reviews와 content 테이블을 조인하여, 실제 사용자들이 남긴 리뷰 평점(score)의 평균이 가장 낮은 장르(genre) 1개를 조회하세요.", "hint": "content 테이블의 rating이 아닌, reviews 테이블의 score 평균을 구해야 합니다.", "answer": "SELECT c.genre, AVG(r.score) as user_avg_score\nFROM reviews r\nJOIN content c ON r.content_id = c.content_id\nGROUP BY c.genre\nORDER BY user_avg_score ASC\nLIMIT 1;"},
        {"title": "19. 중도 이탈이 많은 영화", "difficulty": "중급", "question": "watch_history 테이블에서 완주하지 못한(completed=0) 횟수가 가장 많은 콘텐츠 아이디를 조회하세요.", "hint": "WHERE 절로 이탈 기록만 필터링한 후 빈도를 집계합니다.", "answer": "SELECT content_id, COUNT(*) as drop_count\nFROM watch_history\nWHERE completed = 0\nGROUP BY content_id\nORDER BY drop_count DESC\nLIMIT 1;"},
        {"title": "20. 프리미엄 유저의 평균 구독 기간", "difficulty": "중급", "question": "subscriptions 테이블에서 'premium' 요금제를 사용하는 유저들의 평균 구독 일수를 구하세요. (종료일과 시작일의 차이)", "hint": "날짜 빼기 연산을 적용하여 평균을 구하세요. (SQLite의 경우 JULIANDAY를 활용할 수 있습니다.)", "answer": "SELECT AVG(CAST(JULIANDAY(end_date) - JULIANDAY(start_date) AS INTEGER)) as avg_premium_days\nFROM subscriptions\nWHERE plan = 'premium';"},
        
        # 고급 (10문제)
        {"title": "21. 콘텐츠별 시청 완주율 (Completion Rate)", "difficulty": "고급", "question": "각 콘텐츠(title)별로 시청이 시작된 전체 횟수 대비 끝까지 완주(completed=1)한 횟수의 비율(퍼센트)을 계산하여 완주율이 가장 높은 상위 5개 콘텐츠를 조회하세요. 단, 최소 3회 이상 시청된 콘텐츠만 대상으로 합니다.", "hint": "콘텐츠별 총 시청 수와 완주 수를 SUM(CASE WHEN ...) 등을 이용해 집계하고 조건(HAVING)을 적용하세요.", "answer": "WITH WatchStats AS (\n    SELECT c.title, \n           COUNT(*) as total_views,\n           SUM(CASE WHEN w.completed = 1 THEN 1 ELSE 0 END) as completed_views\n    FROM watch_history w\n    JOIN content c ON w.content_id = c.content_id\n    GROUP BY c.title\n    HAVING COUNT(*) >= 3\n)\nSELECT title, \n       CAST(completed_views AS FLOAT) / total_views * 100 as completion_rate\nFROM WatchStats\nORDER BY completion_rate DESC\nLIMIT 5;"},
        {"title": "22. 몰아보기(Binge-Watching) 유저 찾기", "difficulty": "고급", "question": "하루(같은 날짜)에 서로 다른 콘텐츠를 3개 이상 완주(completed=1)한 적이 있는 열성 시청자(user_id)와 그 날짜를 조회하세요.", "hint": "watched_at에서 날짜 부분(SUBSTR)만 추출하여 유저와 날짜별로 그룹핑한 뒤 고유 콘텐츠 ID의 개수를 검사하세요.", "answer": "SELECT user_id, SUBSTR(watched_at, 1, 10) as watch_date, COUNT(DISTINCT content_id) as unique_completed\nFROM watch_history\nWHERE completed = 1\nGROUP BY user_id, SUBSTR(watched_at, 1, 10)\nHAVING COUNT(DISTINCT content_id) >= 3;"},
        {"title": "23. 평점과 실제 리뷰 점수 간의 괴리율 분석", "difficulty": "고급", "question": "플랫폼에 등록된 공식 평점(rating)과 유저들이 남긴 실제 평균 리뷰 평점(score) 간의 차이(절댓값)가 가장 큰 콘텐츠 3개의 제목과 차이값을 조회하세요. (최소 2개 이상의 리뷰가 있는 콘텐츠 한정)", "hint": "reviews 테이블에서 평균을 구하는 CTE를 만든 뒤 content 테이블의 rating과 빼고 ABS() 함수로 절댓값을 구합니다.", "answer": "WITH UserScore AS (\n    SELECT content_id, AVG(score) as avg_score, COUNT(*) as review_count\n    FROM reviews\n    GROUP BY content_id\n    HAVING COUNT(*) >= 2\n)\nSELECT c.title, ABS(c.rating - u.avg_score) as rating_gap\nFROM content c\nJOIN UserScore u ON c.content_id = u.content_id\nORDER BY rating_gap DESC\nLIMIT 3;"},
        {"title": "24. 유저별 누적 시청 시간 흐름", "difficulty": "고급", "question": "특정 유저('U_0010')의 시간에 따른 누적 시청 시간(Running Total of watched_sec) 변화를 분석하려 합니다. 시청 시간(watched_at)을 오름차순 정렬하여 각 시청 기록마다 현재까지 누적된 시청 초(sec)를 'running_sec' 컬럼으로 조회하세요.", "hint": "윈도우 함수 SUM() OVER(ORDER BY watched_at)를 사용하세요.", "answer": "SELECT watch_id, watched_at, watched_sec, \n       SUM(watched_sec) OVER(ORDER BY watched_at ASC) as running_sec\nFROM watch_history\nWHERE user_id = 'U_0010'\nORDER BY watched_at ASC;"},
        {"title": "25. 첫 시청부터 두 번째 시청까지 걸린 시간", "difficulty": "고급", "question": "플랫폼 리텐션 분석을 위해 유저들이 가입 후 처음 시청한 기록과 두 번째 시청한 기록 사이의 시간차를 계산하려고 합니다. 유저별로 첫 시청 시간과 두 번째 시청 시간을 구한 뒤 그 차이(일수 기준)의 평균을 조회하세요.", "hint": "ROW_NUMBER()로 순위를 매긴 서브쿼리에서 1순위와 2순위 시간만 추출하여 조인하거나 피벗한 뒤 평균을 구하세요.", "answer": "WITH RankedHistory AS (\n    SELECT user_id, watched_at,\n           ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY watched_at ASC) as rn\n    FROM watch_history\n), FirstSecond AS (\n    SELECT user_id,\n           MAX(CASE WHEN rn = 1 THEN watched_at END) as first_watch,\n           MAX(CASE WHEN rn = 2 THEN watched_at END) as second_watch\n    FROM RankedHistory\n    WHERE rn <= 2\n    GROUP BY user_id\n    HAVING COUNT(*) = 2\n)\nSELECT AVG(CAST(JULIANDAY(second_watch) - JULIANDAY(first_watch) AS INTEGER)) as avg_days_between\nFROM FirstSecond;"},
        {"title": "26. 직전 시청 콘텐츠 대비 장르 변경 패턴 (LAG)", "difficulty": "고급", "question": "유저가 연속으로 시청할 때 장르를 바꾸는지 확인하기 위해 윈도우 함수 LAG()를 활용해봅니다. 'U_0025' 유저의 시청 기록에서, 바로 직전에 시청한 콘텐츠의 장르와 현재 시청한 콘텐츠의 장르가 달라진 경우의 횟수를 구하세요.", "hint": "LAG()를 이용해 직전 장르를 구하는 CTE를 작성하고, 현재 장르와 일치하지 않는 경우를 필터링하세요.", "answer": "WITH UserWatchSequence AS (\n    SELECT w.watched_at, c.genre,\n           LAG(c.genre) OVER(ORDER BY w.watched_at ASC) as prev_genre\n    FROM watch_history w\n    JOIN content c ON w.content_id = c.content_id\n    WHERE w.user_id = 'U_0025'\n)\nSELECT COUNT(*) as genre_change_count\nFROM UserWatchSequence\nWHERE prev_genre IS NOT NULL AND genre != prev_genre;"},
        {"title": "27. 요금제 등급 업그레이드 유저 (LEAD)", "difficulty": "고급", "question": "subscriptions 테이블에서 같은 유저가 구독을 연장할 때, 기존 요금제보다 더 비싼 요금제('free' -> 'basic' 또는 'basic' -> 'premium' 등)로 업그레이드한 이력이 있는 유저의 아이디를 모두 찾으세요.", "hint": "LEAD() 또는 LAG()를 써서 이전 구독 요금제와 이후 요금제를 나란히 둔 뒤, 등급 비교 로직(조건 분기)을 사용하세요.", "answer": "WITH PlanSeq AS (\n    SELECT user_id, plan, start_date,\n           LEAD(plan) OVER(PARTITION BY user_id ORDER BY start_date ASC) as next_plan\n    FROM subscriptions\n)\nSELECT DISTINCT user_id\nFROM PlanSeq\nWHERE next_plan IS NOT NULL \n  AND ((plan = 'free' AND next_plan IN ('basic', 'premium')) \n       OR (plan = 'basic' AND next_plan = 'premium'));"},
        {"title": "28. 시리즈물 연속 정주행 그룹 탐지", "difficulty": "고급", "question": "유저가 동일한 'series' 장르의 콘텐츠들을 하루 안에 연속해서 3개 이상 시청한 경우를 '정주행(Binge)'으로 정의합니다. 이러한 정주행 기록이 한 번이라도 있는 유저들의 아이디를 추출하세요.", "hint": "유저, 날짜, 장르(type='series')로 묶은 뒤 시청한 횟수가 3 이상인지 필터링합니다.", "answer": "WITH SeriesWatches AS (\n    SELECT w.user_id, SUBSTR(w.watched_at, 1, 10) as watch_date, c.type, COUNT(*) as cnt\n    FROM watch_history w\n    JOIN content c ON w.content_id = c.content_id\n    WHERE c.type = 'series'\n    GROUP BY w.user_id, SUBSTR(w.watched_at, 1, 10), c.type\n)\nSELECT DISTINCT user_id\nFROM SeriesWatches\nWHERE cnt >= 3;"},
        {"title": "29. 구독 기간 내 시청 활동성 랭킹", "difficulty": "고급", "question": "유저들의 활성도를 평가하기 위해, 각 유저별로 '자신의 전체 활성(active) 구독 기간(일수 총합)' 대비 '총 누적 시청 시간(초)'의 비율(활성도 점수)을 구하고 가장 활성도가 높은 상위 3명을 구하세요.", "hint": "subscriptions에서 총 active 일수를 구하는 CTE와, watch_history에서 총 시청 초를 구하는 CTE를 조인하여 비율을 계산합니다.", "answer": "WITH SubDays AS (\n    SELECT user_id, SUM(CAST(JULIANDAY(end_date) - JULIANDAY(start_date) AS INTEGER)) as total_active_days\n    FROM subscriptions\n    WHERE status = 'active'\n    GROUP BY user_id\n), WatchSec AS (\n    SELECT user_id, SUM(watched_sec) as total_watch_sec\n    FROM watch_history\n    GROUP BY user_id\n)\nSELECT s.user_id, \n       CAST(w.total_watch_sec AS FLOAT) / s.total_active_days as activity_score\nFROM SubDays s\nJOIN WatchSec w ON s.user_id = w.user_id\nWHERE s.total_active_days > 0\nORDER BY activity_score DESC\nLIMIT 3;"},
        {"title": "30. 장르 취향 프로파일링 (최애 장르 찾기)", "difficulty": "고급", "question": "각 유저별로 가장 시청 시간(watched_sec)이 긴 '최애 장르'를 추출하세요. 유저 아이디와 그 유저의 1순위 장르, 그리고 해당 장르의 총 시청 시간을 조회하되, 여러 장르가 1순위라면 윈도우 함수를 통해 하나만 가져오도록 합니다.", "hint": "유저-장르별 총 시청 시간을 구한 뒤 ROW_NUMBER()로 파티셔닝(유저 단위)하여 1위를 골라냅니다.", "answer": "WITH UserGenreSec AS (\n    SELECT w.user_id, c.genre, SUM(w.watched_sec) as total_sec\n    FROM watch_history w\n    JOIN content c ON w.content_id = c.content_id\n    GROUP BY w.user_id, c.genre\n), RankedGenres AS (\n    SELECT user_id, genre, total_sec,\n           ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY total_sec DESC) as rnk\n    FROM UserGenreSec\n)\nSELECT user_id, genre, total_sec\nFROM RankedGenres\nWHERE rnk = 1;"}
    ]
}
